version: "3.9"
name: ai-stack


services:
ai-service:
build: ./ai-service
image: docker.io/srinivasulu2004/ai-service:${TAG-latest}
expose:
- "9000"
environment:
- PYTHONUNBUFFERED=1
healthcheck:
test: ["CMD", "curl", "-fsS", "http://localhost:9000/health"]
interval: 30s
timeout: 3s
retries: 3


backend:
build: ./backend
image: docker.io/srinivasulu2004/backend:${TAG-latest}
depends_on:
ai-service:
condition: service_healthy
expose:
- "8000"
environment:
- AI_URL=http://ai-service:9000
healthcheck:
test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
interval: 30s
timeout: 3s
retries: 3
