version: "3.9"

services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"   # Only expose gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - ai-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: my-frontend:latest
    container_name: frontend
    # No "ports" → only accessible inside Docker network
    depends_on:
      - backend
      - ai-service

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-backend:latest
    container_name: backend
    # No "ports" → only accessible inside Docker network
    depends_on:
      - ai-service

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    image: my-ai-service:latest
    container_name: ai-service
    # No "ports" → only accessible inside Docker network
